const std = @import("std");
const Cards = @import("./evaluator/cards/cards.zig");

pub fn get_card(str: []const u8) Cards.Card {
    const num = std.fmt.parseInt(u16, str[0 .. str.len - 1], 10) catch unreachable;

    return switch (num) {
        0 => Cards.CardFactory(Cards.Rank.ace, Cards.Suit.spade),
        1 => Cards.CardFactory(Cards.Rank.two, Cards.Suit.spade),
        2 => Cards.CardFactory(Cards.Rank.three, Cards.Suit.spade),
        3 => Cards.CardFactory(Cards.Rank.four, Cards.Suit.spade),
        4 => Cards.CardFactory(Cards.Rank.five, Cards.Suit.spade),
        5 => Cards.CardFactory(Cards.Rank.six, Cards.Suit.spade),
        6 => Cards.CardFactory(Cards.Rank.seven, Cards.Suit.spade),
        7 => Cards.CardFactory(Cards.Rank.eight, Cards.Suit.spade),
        8 => Cards.CardFactory(Cards.Rank.nine, Cards.Suit.spade),
        9 => Cards.CardFactory(Cards.Rank.ten, Cards.Suit.spade),
        10 => Cards.CardFactory(Cards.Rank.jack, Cards.Suit.spade),
        11 => Cards.CardFactory(Cards.Rank.queen, Cards.Suit.spade),
        12 => Cards.CardFactory(Cards.Rank.king, Cards.Suit.spade),
        13 => Cards.CardFactory(Cards.Rank.ace, Cards.Suit.heart),
        14 => Cards.CardFactory(Cards.Rank.two, Cards.Suit.heart),
        15 => Cards.CardFactory(Cards.Rank.three, Cards.Suit.heart),
        16 => Cards.CardFactory(Cards.Rank.four, Cards.Suit.heart),
        17 => Cards.CardFactory(Cards.Rank.five, Cards.Suit.heart),
        18 => Cards.CardFactory(Cards.Rank.six, Cards.Suit.heart),
        19 => Cards.CardFactory(Cards.Rank.seven, Cards.Suit.heart),
        20 => Cards.CardFactory(Cards.Rank.eight, Cards.Suit.heart),
        21 => Cards.CardFactory(Cards.Rank.nine, Cards.Suit.heart),
        22 => Cards.CardFactory(Cards.Rank.ten, Cards.Suit.heart),
        23 => Cards.CardFactory(Cards.Rank.jack, Cards.Suit.heart),
        24 => Cards.CardFactory(Cards.Rank.queen, Cards.Suit.heart),
        25 => Cards.CardFactory(Cards.Rank.king, Cards.Suit.heart),
        26 => Cards.CardFactory(Cards.Rank.ace, Cards.Suit.club),
        27 => Cards.CardFactory(Cards.Rank.two, Cards.Suit.club),
        28 => Cards.CardFactory(Cards.Rank.three, Cards.Suit.club),
        29 => Cards.CardFactory(Cards.Rank.four, Cards.Suit.club),
        30 => Cards.CardFactory(Cards.Rank.five, Cards.Suit.club),
        31 => Cards.CardFactory(Cards.Rank.six, Cards.Suit.club),
        32 => Cards.CardFactory(Cards.Rank.seven, Cards.Suit.club),
        33 => Cards.CardFactory(Cards.Rank.eight, Cards.Suit.club),
        34 => Cards.CardFactory(Cards.Rank.nine, Cards.Suit.club),
        35 => Cards.CardFactory(Cards.Rank.ten, Cards.Suit.club),
        36 => Cards.CardFactory(Cards.Rank.jack, Cards.Suit.club),
        37 => Cards.CardFactory(Cards.Rank.queen, Cards.Suit.club),
        38 => Cards.CardFactory(Cards.Rank.king, Cards.Suit.club),
        39 => Cards.CardFactory(Cards.Rank.ace, Cards.Suit.diamond),
        40 => Cards.CardFactory(Cards.Rank.two, Cards.Suit.diamond),
        41 => Cards.CardFactory(Cards.Rank.three, Cards.Suit.diamond),
        42 => Cards.CardFactory(Cards.Rank.four, Cards.Suit.diamond),
        43 => Cards.CardFactory(Cards.Rank.five, Cards.Suit.diamond),
        44 => Cards.CardFactory(Cards.Rank.six, Cards.Suit.diamond),
        45 => Cards.CardFactory(Cards.Rank.seven, Cards.Suit.diamond),
        46 => Cards.CardFactory(Cards.Rank.eight, Cards.Suit.diamond),
        47 => Cards.CardFactory(Cards.Rank.nine, Cards.Suit.diamond),
        48 => Cards.CardFactory(Cards.Rank.ten, Cards.Suit.diamond),
        49 => Cards.CardFactory(Cards.Rank.jack, Cards.Suit.diamond),
        50 => Cards.CardFactory(Cards.Rank.queen, Cards.Suit.diamond),
        51 => Cards.CardFactory(Cards.Rank.king, Cards.Suit.diamond),
        else => unreachable,
    };
}
